name:                juelz
version:             0.1.0.0
github:              "juliengrimault/juelz"
license:             BSD3
author:              "Julien Grimault"
maintainer:          "grimault.julien@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/juliengrimault/juelz#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- shake
- slick
- text

executables:
  juelz-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  juelz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - juelz
